//! # Device Model
//!
//! This module provides a generic, extensible device driver framework for the kernel.
//! It allows drivers to register devices, expose methods (operations), and dispatch
//! calls to those methods from userspace or other kernel components.
//!
//! ## Overview
//!
//! The device model is built around the following concepts:
//!
//! - **DeviceId**: A unique, generation‑aware identifier for a device. It encodes
//!   both an index into the global device registry and a generation number to
//!   detect stale handles.
//!
//! - **Device**: A struct that holds a device's name, parent, driver‑specific data,
//!   and a map of method IDs to function pointers (`DeviceMethod`).
//!
//! - **Registry**: A global, lock‑protected array of optional `Device` boxes. It
//!   manages allocation, deallocation, and lookup of devices.
//!
//! - **DeviceMethod**: An `extern "C"` function that takes a `DeviceId` and an
//!   opaque `usize` argument, returning a `DeviceResult`. This ABI is stable
//!   and callable from any context.
//!
//! ## Method Dispatch
//!
//! Method calls are performed via `call_method(id, method_id, arg)`, which:
//! 1. Looks up the device in the registry.
//! 2. Finds the method in the device's method table.
//! 3. Calls the method with the provided argument.
//!
//! Methods are identified by a `u64` hash (typically a FNV‑1a hash of a string
//! like `"fb.get_info"`), generated via the `interface!` macro from `driverkit`.
//!
//! ## Driver Data
//!
//! Each device can store an opaque `usize` (typically a pointer to driver‑specific
//! state) in `driver_data`. This is set via `set_driver_data` and retrieved with
//! `get_driver_data`.
//!
//! ## Usage Example (from `etc/fb.rs`)
//!
//! ```ignore
//! let mut dev = Device::new("fb0");
//! dev.add_method(FB_GET_INFO, fb_get_info_method);
//! dev.add_method(FB_CLEAR, fb_clear_method);
//! dev.add_method(FB_PLOT, fb_plot_method);
//!
//! let state = Box::new(FbState { ... });
//! dev.driver_data = Box::into_raw(state) as usize;
//!
//! let dev_id = crate::dev::register_device(dev).unwrap();
//! ```
//!
//! ## Safety
//!
//! The device model is safe to use from multiple CPUs; the registry is protected
//! by a `Nutex` (interrupt‑disabling spinlock). However, driver authors must
//! ensure that their method implementations are thread‑safe and handle any
//! necessary synchronization internally.
//!
//! ## Limitations
//!
//! - Maximum of 4096 devices.
//! - Methods are `extern "C"` and cannot capture context; driver state must be
//!   accessed via `driver_data` or global structures.

use crate::sync::Nutex;
use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::string::String;

// ============================================================================
// TYPES
// ============================================================================

/// A 64‑bit identifier for a device method.
///
/// Typically generated by hashing a method name (e.g., `"fb.get_info"`) using
/// FNV‑1a via the `interface!` macro.
pub type MethodId = u64;

extrum! {
    /// Device operation status codes.
    ///
    /// These are returned by methods as part of `DeviceResult`. A `SUCCESS` status
    /// indicates the operation succeeded; any other value indicates an error.
    #[derive(Clone, Copy, PartialEq)]
    pub enum DeviceStatus: usize {
        SUCCESS = 0,
        NOT_FOUND = 1,
        INVALID_ARG = 2,
        BUSY = 3,
        IO_ERROR = 4,
        UNSUPPORTED = usize::MAX,
    }
}

/// The result of a device method call.
///
/// This C‑compatible struct is returned by all `DeviceMethod` functions.
/// It contains a `value` (e.g., number of bytes written) and a `status` code.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct DeviceResult {
    /// The return value of the method (semantics depend on the method).
    pub value: usize,
    /// The status code indicating success or error.
    pub status: DeviceStatus,
}

impl DeviceResult {
    /// Creates a new result with the given value and status.
    #[inline]
    pub const fn new(value: usize, status: DeviceStatus) -> Self {
        Self { value, status }
    }

    /// Creates a successful result.
    #[inline]
    pub const fn ok(value: usize) -> Self {
        Self { value, status: DeviceStatus::SUCCESS }
    }

    /// Creates an error result with the given status.
    #[inline]
    pub const fn err(status: DeviceStatus) -> Self {
        Self { value: 0, status }
    }

    /// Converts this result into a Rust `Result<usize, DeviceStatus>`.
    #[inline]
    pub fn as_result(self) -> Result<usize, DeviceStatus> {
        if self.status == DeviceStatus::SUCCESS {
            Ok(self.value)
        } else {
            Err(self.status)
        }
    }

    /// Constructs a `DeviceResult` from a Rust `Result`.
    #[inline]
    pub fn from_result(res: Result<usize, DeviceStatus>) -> Self {
        match res {
            Ok(value) => Self::ok(value),
            Err(status) => Self::err(status),
        }
    }
}

/// A device method function pointer.
///
/// All device methods have this ABI: they take a `DeviceId` and an opaque
/// `usize` argument (typically a pointer to a method‑specific argument struct),
/// and return a `DeviceResult`.
pub type DeviceMethod = extern "C" fn(DeviceId, usize) -> DeviceResult;

/// A unique, generation‑aware device identifier.
///
/// The ID is a 32‑bit value that encodes:
/// - Lower 20 bits: device index (0..1023)
/// - Upper 12 bits: generation number (incremented on each registration at the
///   same index)
///
/// This prevents use‑after‑free bugs: a stale `DeviceId` from a previous
/// incarnation of a device at the same index will have a different generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct DeviceId(u32);

impl DeviceId {
    /// Returns the index part of the ID.
    #[inline]
    pub const fn index(self) -> usize {
        (self.0 & 0x000FFFFF) as usize
    }

    /// Returns the generation part of the ID.
    #[inline]
    pub const fn generation(self) -> u16 {
        (self.0 >> 20) as u16
    }

    /// Constructs a new `DeviceId` from an index and generation.
    #[inline]
    pub const fn new(index: usize, gen_: u16) -> Self {
        Self(((gen_ as u32) << 20) | (index as u32))
    }

    /// Returns `true` if this is the null device ID.
    #[inline]
    pub const fn is_null(self) -> bool {
        self.0 == 0
    }

    /// The null device ID, representing an invalid device.
    pub const NULL: Self = Self(0);
}

// ============================================================================
// DEVICE STRUCTURE
// ============================================================================

/// A registered device.
///
/// This struct holds all information about a device, including its name,
/// parent relationship, driver‑specific data, and the table of methods it
/// supports.
#[repr(C, align(128))]
pub struct Device {
    /// The assigned device ID (set by the registry upon registration).
    pub id: DeviceId,

    /// Human‑readable device name (e.g., `"fb0"`, `"sda"`).
    pub name: String,

    /// Optional parent device ID (for hierarchical device trees).
    pub parent: Option<DeviceId>,

    /// Opaque driver‑specific data (e.g., pointer to driver state).
    pub driver_data: usize,

    /// Method table: mapping from method ID to function pointer.
    pub methods: BTreeMap<MethodId, DeviceMethod>,
}

impl Device {
    /// Creates a new device with the given name.
    ///
    /// The device is initially unregistered (`id` is `NULL`) and has no methods.
    pub fn new(name: &str) -> Self {
        Self {
            id: DeviceId::NULL,
            name: String::from(name),
            parent: None,
            driver_data: 0,
            methods: BTreeMap::new(),
        }
    }

    /// Adds a method to the device's method table.
    ///
    /// # Arguments
    /// * `method_id` – The unique identifier for the method.
    /// * `method`    – The function pointer to be called.
    pub fn add_method(&mut self, method_id: MethodId, method: DeviceMethod) {
        self.methods.insert(method_id, method);
    }

    /// Retrieves a method by its ID, if present.
    pub fn get_method(&self, method_id: MethodId) -> Option<DeviceMethod> {
        self.methods.get(&method_id).copied()
    }
}

// Export![Device::new => VtDeviceNew, since kernel 0.1];
Export! {
    pub fn VtDeviceNew(name: &str) -> Option<Box<Device>>
    where kernel 0.1 {
        Some(Box::new(Device::new(name)))
    }
}

// ============================================================================
// GLOBAL REGISTRY
// ============================================================================

/// Maximum number of devices that can be registered.
const MAX_DEVICES: usize = 4096;

/// The global device registry.
///
/// This struct maintains an array of optional `Device` boxes, along with
/// a generation counter for each slot to support generation‑aware IDs.
struct Registry {
    /// The actual device storage. `None` means the slot is free.
    devices: [Option<Box<Device>>; MAX_DEVICES],

    /// Generation counter for each slot, incremented on each registration.
    generations: [u16; MAX_DEVICES],
}

impl Registry {
    /// Creates a new, empty registry.
    const fn new() -> Self {
        Self {
            devices: [const { None }; MAX_DEVICES],
            generations: [0; MAX_DEVICES],
        }
    }

    /// Registers a device, assigning it a unique `DeviceId`.
    ///
    /// Returns `Some(id)` if a free slot was found, or `None` if the registry
    /// is full.
    fn register(&mut self, mut device: Box<Device>) -> Option<DeviceId> {
        for (i, slot) in self.devices.iter_mut().enumerate() {
            if slot.is_none() {
                // Increment the generation for this slot.
                self.generations[i] = self.generations[i].wrapping_add(1);
                let gen_ = self.generations[i];
                let id = DeviceId::new(i, gen_);

                device.id = id;
                *slot = Some(device);
                return Some(id);
            }
        }
        None
    }

    /// Unregisters a device by its ID.
    ///
    /// Returns `true` if the device was found and removed, `false` otherwise.
    fn unregister(&mut self, id: DeviceId) -> bool {
        let idx = id.index();
        if idx >= MAX_DEVICES {
            return false;
        }

        if let Some(device) = &self.devices[idx]
        && device.id.generation() == id.generation() {
            self.devices[idx] = None;
            return true;
        }
        false
    }

    /// Looks up a device by its ID.
    ///
    /// Returns `Some(&Device)` if the ID is valid and the generation matches,
    /// otherwise `None`.
    fn get_device(&self, id: DeviceId) -> Option<&Device> {
        let idx = id.index();
        if idx >= MAX_DEVICES {
            return None;
        }

        if let Some(device) = &self.devices[idx]
        && device.id.generation() == id.generation() {
            return Some(device);
        }
        None
    }
}

/// The global device registry, protected by a `Nutex` (interrupt‑disabling
/// spinlock) for safe concurrent access from multiple CPUs.
static REGISTRY: Nutex<Registry> = Nutex::new(Registry::new());

// ============================================================================
// PUBLIC API
// ============================================================================

/// Initializes the device model.
///
/// Currently a no‑op, but called from `main()` to mark the subsystem as ready.
pub fn init() {
    info!("Initialized");
}

/// Registers a new device with the system.
///
/// The device is inserted into the global registry and assigned a unique
/// `DeviceId`. The device's `id` field is updated to reflect the assigned ID.
///
/// # Returns
/// `Some(id)` on success, `None` if the registry is full.
pub fn register_device(device: Box<Device>) -> Option<DeviceId> {
    REGISTRY.lock().register(device)
}

/// Unregisters a device by its ID.
///
/// # Returns
/// `true` if the device was found and removed, `false` otherwise.
pub fn unregister_device(id: DeviceId) -> bool {
    REGISTRY.lock().unregister(id)
}

/// Sets the driver‑specific data for a device.
///
/// # Returns
/// `true` if the device was found and the data was updated, `false` otherwise.
pub fn set_driver_data(id: DeviceId, data: usize) -> bool {
    let mut guard = REGISTRY.lock();
    if let Some(device) = guard.devices[id.index()].as_mut()
    && device.id.generation() == id.generation() {
        device.driver_data = data;
        return true;
    }
    false
}

/// Retrieves the driver‑specific data for a device.
///
/// # Returns
/// `Some(data)` if the device exists, `None` otherwise.
pub fn get_driver_data(id: DeviceId) -> Option<usize> {
    let guard = REGISTRY.lock();
    guard.get_device(id).map(|dev| dev.driver_data)
}

/// Invokes a method on a device.
///
/// This function looks up the device and method, then calls the method with
/// the provided argument. The registry lock is released before the method call
/// to avoid deadlocks if the method itself tries to access the registry.
///
/// # Returns
/// A `DeviceResult` containing the method's return value and status.
pub fn call_method(id: DeviceId, method_id: MethodId, arg: usize) -> DeviceResult {
    let guard = REGISTRY.lock();

    // Look up the device
    let device = match guard.get_device(id) {
        Some(dev) => dev,
        None => return DeviceResult::err(DeviceStatus::NOT_FOUND),
    };

    // Look up the method
    let method = match device.get_method(method_id) {
        Some(m) => m,
        None => return DeviceResult::err(DeviceStatus::UNSUPPORTED),
    };

    // Release the lock before calling the method
    drop(guard);

    // Invoke the method
    method(id, arg)
}
